dist: xenial
    
sudo: required

language: csharp
mono: none

dotnet: 3.1

solution: GenHTTP.Gateway.sln

env:
  - DOTNET_ROLL_FORWARD=Major

addons:
  sonarcloud:
    organization: "kaliumhexacyanoferrat"

install:
  - git fetch --unshallow --tags
  
script:
  - dotnet tool restore
  - dotnet sonarscanner begin /k:"GenHTTP.Gateway" /d:sonar.login="$SONAR_TOKEN" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*"
  - dotnet build GenHTTP.Gateway.sln -c Release
  - dotnet test -c Release --no-build GenHTTP.Gateway.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ParallelizeTestCollections=false /p:Exclude=\"[xunit.*]*,[*Tests*]*\" 
  - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"