hosts:

  # configuration for a specific host
  # duplicate this entry to add another host
  domain1.com:

    # uncomment this block to support SSL
    # mount your certificates in /app/certs

    # security:
    #   certificate:
    #    pfx: domain1.pfx

    # the web page that will be shown if domain1.com is called
    default:
      destination: http://10.0.0.2:8080

    # additional routes to be accessible via the gateway
    routes:

      # routes can be chained, the children of this entry will be
      # accessible via domain1.com/admin/
      admin:

        routes:

          # domain1.com/admin/portainer/
          portainer:
            destination: http://10.0.0.2:9000

          # domain1.com/admin/pi-hole/
          pi-hole:
            destination: http://10.0.0.3/admin/

          # domain1.com/admin/files/
          files:
            listing: ./
            