name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOTNET_ROLL_FORWARD: Major

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore tools
      run: dotnet tool restore
    - name: Begin scan
      run: dotnet sonarscanner begin /o:"kaliumhexacyanoferrat" /k:"GenHTTP.Gateway" /d:sonar.login="$SONAR_TOKEN" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.host.url="https://sonarcloud.io"
    - name: Build project
      run: dotnet build GenHTTP.Gateway.sln -c Release
    - name: Test project
      run: dotnet test -c Release --no-build GenHTTP.Gateway.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ParallelizeTestCollections=false /p:Exclude=\"[xunit.*]*,[*Tests*]*\" 
    - name: End scan
      run: dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
